included:
  - Sources

trailing_whitespace:
  ignores_empty_lines: true

line_length:
  warning: 120
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true 

disabled_rules:
  - todo

identifier_name:
  excluded: # excluded via string array
    - id