version: '3.7'

services:
    push-service:
        environment:
            POSTGRES_URL: postgres://postgres:mysecretpassword@db:5432
            REDIS_URL: redis://redis:6379
        build:
            context: ${BACK_PUSH_SERVICE_CONTEXT:-.}/
        ports:
            - ${ITLAB_PUSH_SERVICE_PORT:-8080}:${ITLAB_PUSH_SERVICE_PORT:-8080}

    db:
        image: postgres:latest
        environment: 
            POSTGRES_PASSWORD: mysecretpassword
            
    redis:
        image: redis:latest
        ports: 
            - 6379:6379
    
secrets:
    settings.json:
        file: "${BACK_PUSH_SERVICE_CONTEXT:-.}/Private/json/settings.json"
    FCM.json:
        file: "${BACK_PUSH_SERVICE_CONTEXT:-.}/Private/json/FCM.json"
    APNs.p8:
        file: "${BACK_PUSH_SERVICE_CONTEXT:-.}/Private/APNs.p8"

