version: '3.7'

services:
  push-service:
    image: registry.rtuitlab.dev/rtuitlab/itlab-push-service:${ITLAB_SERVICE_TAG-latest}
    environment:
      - POSTGRES_URL=${ITLAB_PUSH_SERVICE_DB?Provice postgres connection string ITLAB_PUSH_SERVICE_DB}
      - REDIS_URL=${ITLAB_PUSH_SERVICE_REDIS:-redis://localhost:6379}
      - JWT_URL=${ITLAB_PUSH_SERVICE_JWT:-}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
    - net
networks:
  net:
    driver: overlay
