version: '3.7'

services:
  app:
    environment:
        POSTGRES_URL: postgres://postgres:mysecretpassword@db:5432
    build:
      context: .
    ports:
      - '5510:8080'

  db:
    image: postgres:latest
    environment: 
        POSTGRES_PASSWORD: mysecretpassword

secrets:
  settings.json:
    file: "Private/json/settings.json"
  FCM.json:
    file: "Private/json/FCM.json"
  APNs.p8:
    file: "Private/APNs.p8"

